# créer le jeu
POST http://localhost:1337/api/free-games
Content-Type: application/json

{
    "data": {
        "nom":"aaa",
        "description":"fff",
        "image":"xxx"
    }
}

###
# recupère tout les jeux 
GET http://localhost:1337/api/free-games

###
# récupère un jeu
GET http://localhost:1337/api/free-games/2

###
# modifier un jeux
PUT http://localhost:1337/api/free-games/1
Content-Type: application/json

{
    "data": {
        "nom":"RLS",
        "description":"pas mal pour passer le temps",
        "imag":"..."
    }
}

###
# supprimer un jeu
DELETE http://localhost:1337/api/free-games/5